package org.automation.objectBuilder;

import org.automation.objectBuilder.pages.BillsPage;

public class ObjectBuilder {
    public static class BillDetails{
        public static BillsPage getDefaultBillDetails(){
            BillsPage bill = new BillsPage();
            bill.setAmount("1,000");
            bill.setCustomerEmail("yonro@yopmail.com");
            bill.setCustomerPhnNo("918877070727");
            bill.setBillDescription("This is a autogenerated bill.");
            bill.setMemoText("Test memo message");
            bill.setStore("Automation Flow 1");
            return bill;
        }
    }
}
