name: Maven Build

on:
  push:
    branches:
      - '**'  

jobs:
  build:
    runs-on: self-hosted  # You can change this to a different OS if needed

    steps:
    - name: Build with Maven
      run: mvn install -DskipTests
